[workspace]
resolver = "2"
members = [
    "compositor/tos-term",
    "compositor/tos-crypt",
    "compositor/tos-font",
    "compositor/tos-render",
    "compositor/tos-pty",
    "compositor/tos-input",
    "compositor/tos-session",
    "compositor/tos-platform",
    "compositor/tos-system",
    "compositor/tos-compositor",
    "installer",
    "preview",
]

[workspace.package]
version = "0.0.5"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
repository = "https://github.com/m96-chan/tOS"

[workspace.dependencies]
tos-term = { path = "compositor/tos-term" }
tos-crypt = { path = "compositor/tos-crypt" }
tos-font = { path = "compositor/tos-font" }
tos-render = { path = "compositor/tos-render" }
tos-pty = { path = "compositor/tos-pty" }
tos-input = { path = "compositor/tos-input" }
tos-session = { path = "compositor/tos-session" }
tos-platform = { path = "compositor/tos-platform" }
tos-system = { path = "compositor/tos-system" }
tos-compositor = { path = "compositor/tos-compositor" }
tos-install = { path = "installer" }
tos-preview = { path = "preview" }
libc = "0.2"

[profile.release]
opt-level = 3
lto = "thin"
panic = "abort"
